# This files has the default values for dojot API Gateway variables

dojot_internal_http_port: 8000
dojot_internal_api_config_port: 8001

dojot_apigw_version: "{{ dojot_version }}"

dojot_psql_kong_user: kong
dojot_psql_kong_passwd: kong
dojot_psql_kong_db: kong
