version: "3.7"
services:
  x509-identity-mgmt:
    build:
      context: ./../../
    depends_on:
      - ejbca-db
      - mongo-db
    restart: always
    hostname: "x509-identity-mgmt"
    domainname: "dojot.iot"
    environment:
      DATABASE_JDBC_URL: jdbc:postgresql://ejbca-db:5432/ejbca?characterEncoding=UTF-8
      DATABASE_USER: ejbca
      DATABASE_PASSWORD: ejbca
      EJBCA_PERFORM_DOJOT_SETUP: "true"
      EJBCA_EXTERNAL_ACCESS: "true"
      EJBCA_ADMIN_USER: "true"
      NODE_ENV: production
      MONGO_URI: "mongodb://mongo-db:27017/x509-identity-mgmt"
      MONGO_USER: root
      MONGO_PASS: pass
      MONGO_AUTH_DB: admin
    ports:
      - "3000:3000"
      - "8080:8080"
      - "8443:8443"
    volumes:
      - "ejbca-volume:/mnt/persistent"
    networks:
      - ejbca-bridge
      - mongo-bridge

  #x509-identity-mgmt-other:
  #  build:
  #    context: ./../../
  #  depends_on:
  #    - ejbca-db
  #    - mongo-db
  #  restart: always
  #  hostname: "x509-identity-mgmt-other"
  #  domainname: "dojot.iot"
  #  environment:
  #    DATABASE_JDBC_URL: jdbc:postgresql://ejbca-db:5432/ejbca?characterEncoding=UTF-8
  #    DATABASE_USER: ejbca
  #    DATABASE_PASSWORD: ejbca
  #    EJBCA_PERFORM_DOJOT_SETUP: "true"
  #    EJBCA_EXTERNAL_ACCESS: "true"
  #    EJBCA_ADMIN_USER: "true"
  #    NODE_ENV: production
  #    MONGO_URI: "mongodb://mongo-db:27017/x509-identity-mgmt"
  #    MONGO_USER: root
  #    MONGO_PASS: pass
  #    MONGO_AUTH_DB: admin
  #  ports:
  #    - "23000:3000"
  #    - "28080:8080"
  #    - "28443:8443"
  #  volumes:
  #    - "ejbca-volume:/mnt/persistent"
  #  networks:
  #    - ejbca-bridge
  #    - mongo-bridge

  ejbca-db:
    image: "postgres:9.4.24-alpine"
    restart: always
    environment:
      POSTGRES_DB: ejbca
      POSTGRES_USER: ejbca
      POSTGRES_PASSWORD: ejbca
    ports:
      - "5432:5432"
    volumes:
      - "ejbca-db-volume:/var/lib/postgresql/data"
    networks:
      - ejbca-bridge

  mongo-db:
    image: "mongo"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - "27017:27017"
    volumes:
      - "mongo-db-volume:/data/db"
      - "mongo-db-cfg-volume:/data/configdb"
    networks:
      - mongo-bridge

  #mongo-webadmin:
  #  image: "mongo-express"
  #  restart: always
  #  depends_on:
  #    - mongo-db
  #  environment:
  #    ME_CONFIG_OPTIONS_EDITORTHEME: ambiance
  #    ME_CONFIG_MONGODB_SERVER: mongo-db
  #    ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #    ME_CONFIG_MONGODB_ADMINPASSWORD: pass
  #  ports:
  #    - "8081:8081"
  #  networks:
  #    - mongo-bridge

volumes:
  ejbca-volume:
  ejbca-db-volume:
  mongo-db-volume:
  mongo-db-cfg-volume:

networks:
  ejbca-bridge:
    driver: bridge
  mongo-bridge:
    driver: bridge