FORMAT: 1A
HOST: https://localhost:3000/device-auth/v1
# Device Authentication

API documentation for Device Authentication

# Group device-auth

API to provide credentials for authentication of
devices that communicate with the dojot IoT platform.

## Endpoint issuing credentials[ [/{deviceId}/basic-credentials]

### generates username and password for use in authenticating devices [POST]

A basic authentication token will also be returned.

If deviceId does not have a valid structure or if any of the above conditions are
not answered, a response status of 400 (Bad Request) will be returned, containing a
message detailing the cause of the error.

+ Request issued credential to device (application/json)

    + Headers

            Authorization: Bearer [JWT]

+ Response 200 (application/json)
            
    + Attributes (object)
        - credentials:  (object)
          - username: tenant1@123abc (string)
          - password: AOxRg!v1heGuQ0Y (string)
        - basicAuth: Basic dGVuYW50MUAxMjNhYmM6QU94UmchdjFoZUd1UTBZ (string)

          Credencias

+ Response 400 (application/json)

    + Attributes (object)
        - message: Device is not valid. (string)

            Device is not valid.

+ Response 500 (application/json)

    + Attributes (object)
        - message: A message describing the cause of the error (string)

            A message describing the cause of the error


## Endpoint for authentication[ [/internal/authentication]

### authenticate device [POST]

Positive validation message is returned

+ Request issued credential to device (application/json)

    + Headers

            Authorization: Basic base64encode(username:password)

+ Response 200 (application/json)
            
    + Attributes (object)
        - message: The credential is valid. (string)

          validation

+ Response 401 (application/json)

    + Attributes (object)
        - message: A message describing the cause of the error (string)

            A message describing the cause of the error

+ Response 500 (application/json)

    + Attributes (object)
        - message: A message describing the cause of the error (string)

            A message describing the cause of the error