## This role is responsible for deploying v2k-bridge
- name: dojot - v2k-bridge
  k8s:
    kubeconfig: "{{ dojot_kubeconfig_file_path | default(omit) }}"
    state: present
    definition: "{{ item }}"
  register: result
  until: result.failed == 0
  retries: 30
  delay: 10
  loop:
  - "{{ lookup('template', 'v2k_bridge_cluster.yaml.j2') | from_yaml }}"
  - "{{ lookup('template', 'v2k_bridge_service.yaml.j2') | from_yaml }}"