## This role is responsible for deploying k2v-bridge for dojot epic

- name: dojot - k2v-bridge (Kafka to verne bridge) Objects
  k8s:
    kubeconfig: "{{ dojot_kubeconfig_file_path | default(omit) }}"
    state: present
    definition: "{{ item }}"
  register: result
  until: result.failed == 0
  retries: 30
  delay: 10
  loop:
  - "{{ lookup('template', 'k2v_bridge_service.yaml.j2') | from_yaml }}"
  - "{{ lookup('template', 'k2v_bridge_cluster.yaml.j2') | from_yaml }}"
