## This role is responsible for deploying MongoDB for dojot
# TODO: Support a HA cluster

- name: dojot - MongoDB PVC
  when: dojot_mongodb_persistent_volumes
  k8s:
    kubeconfig: "{{ dojot_kubeconfig_file_path | default(omit) }}"
    state: present
    definition: "{{ lookup('template', 'mongodb_pvc.yaml.j2') | from_yaml }}"
  register: result
  until: result.failed == 0
  retries: 30
  delay: 10

- name: dojot - MongoDB Objects
  k8s:
    kubeconfig: "{{ dojot_kubeconfig_file_path | default(omit) }}"
    state: present
    definition: "{{ item }}"
  register: result
  until: result.failed == 0
  retries: 30
  delay: 10
  loop:
  - "{{ lookup('template', 'mongodb_secret.yaml.j2') | from_yaml }}"
  - "{{ lookup('template', 'mongodb_service.yaml.j2') | from_yaml }}"
  - "{{ lookup('template', 'mongodb_deployment.yaml.j2') | from_yaml }}"
