## This role is responsible for deploying the Auth Service for dojot

- name: dojot - Data Broker Objects
  k8s:
    kubeconfig: "{{ dojot_kubeconfig_file_path | default(omit) }}"
    state: present
    definition: "{{ item }}"
  register: result
  until: result.failed == 0
  retries: 30
  delay: 10
  loop:
  - "{{ lookup('template', 'data_broker_service.yaml.j2') | from_yaml }}"
  - "{{ lookup('template', 'data_broker_redis_service.yaml.j2') | from_yaml }}"
  - "{{ lookup('template', 'data_broker_redis_deployment.yaml.j2') | from_yaml }}"
  - "{{ lookup('template', 'data_broker_deployment.yaml.j2') | from_yaml }}"
