## This role is responsible for deploying verneMq for dojot

- name: dojot - ejbca-node Objects
  k8s:
    kubeconfig: "{{ dojot_kubeconfig_file_path | default(omit) }}"
    state: present
    definition: "{{ item }}"
  register: result
  until: result.failed == 0
  retries: 30
  delay: 10
  loop:
  - "{{ lookup('template', 'ejbca_cluster.yaml.j2') | from_yaml }}"
  - "{{ lookup('template', 'ejbca_external_service.yaml.j2') | from_yaml }}"
  - "{{ lookup('template', 'ejbca_service.yaml.j2') | from_yaml }}"