{
 "title": "Telemetria",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "deviceIds",
    "label": "Device ID",
    "query": "import \"influxdata/influxdb/v1\"\nv1.measurements(bucket: v.bucket)"
   },
   {
    "name": "device",
    "label": "Nome do dispositivo",
    "query": "select label from admin.devices"
   },
   { "name": "field", "label": "Atributo", "query": "select label from admin.attrs" },
   {
    "name": "deviceId",
    "query": "select id from admin.devices where label = '${device}'"
   },
   {
    "name": "fields",
    "query": "select 'dojot.' || label from admin.attrs"
   },
   {
    "name": "devices",
    "label": "Dispositivos",
    "query": "select label from admin.devices"
   },
   {
    "name": "devicesIds",
    "query": "select id from admin.devices where label in (${devices})"
   },
   { "name": "limitVar", "label": "Limite", "query": "1,5,10,15,20,50,100" }
  ]
 },
 "panels": [
  {
   "title": "Dispositivo ID = 10c325",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket:\"devices\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._measurement == \"10c325\" and r._field == \"dojot.temperatura\")\n|> toFloat()"
    }
   ]
  },
  {
   "title": "Painel 1",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": {
    "content": "# Linha com 1 atributo para 1 dispositivo sem uso de variáveis\n\nGráfico simples que exibe o atributo temperatura do dispositivo \"10c325\" ao longo do tempo.\nO range utilizado na query \"aponta\" para o combo de período que está no menu, no topo, onde é possível escolher diversos períodos. Esse range, por sua vez, também é parametrizável, podendo aceitar muitos valores, e não apenas os valores contidos no referido combo.\nA função \"toFloat()\" no final da query é necessária para converter o valor da temperatura de string para float, pois, hoje na Dojot, todos os dados são gravados como string (apesar de recentemente ter sido implementada uma configuração para isso na Dojot, permitindo a gravação e recuperação dos dados do InfluxDB pelos tipos originais)."
   }
  },
  {
   "title": "Dispositivo ID = 10c325",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket:\"devices\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._measurement == \"10c325\" and r._field == \"dojot.temperatura\")\n|> map(fn: (r) => ({r with Temperatura: float(v: r._value)}))\n|> keep(columns: [\"Temperatura\", \"_time\"])"
    },
    {
     "query": "from(bucket:\"devices\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._measurement == \"10c325\" and r._field == \"dojot.umidade\")\n|> map(fn: (r) => ({r with Umidade: float(v: r._value)}))\n|> keep(columns: [\"Umidade\", \"_time\"])"
    }
   ]
  },
  {
   "title": "Painel 2",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": {
    "content": "# Linha com 2 atributos para 1 dispositivo sem uso de variáveis\n\nNesse painel foram usadas duas queries, sendo que cada query consulta um atributo diferente do mesmo dispositivo. Nas queries foi possível definir também os nomes \"Temperatura\" e \"Umidade\" (através das funções map() e keep()) para os atributos consultados, para que sejam exibidos de maneira mais legível no gráfico.\nNas configurações do Grafana no lado direito foi possível definir para cada atributo a posição que cada um seria exibido no gráfico e também a unidade de medida. Para isso foi utilizada a opção \"Add field override\", que é a última opção do lado direito. Após clicar nela, foi selecionada a opção \"Fields with name\" -> \"Add override property\" -> \"Axis > Placement\" para configurar a posição e \"Standard options > Unit\" para as unidades de medida."
   }
  },
  {
   "title": "Temperatura média dispositivo ID = 10c325",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket:\"devices\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._measurement == \"10c325\" and r._field == \"dojot.temperatura\")\n|> toFloat()\n|> mean()"
    }
   ]
  },
  {
   "title": "Painel 3",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": {
    "content": "# \"Label\" com 1 atributo para 1 dispositivo sem uso de variáveis com função de agregação (média, máx, mín)\n\nNesse painel, obtemos o valor médio de temperatura através da função \"mean()\" na query. O período escolhido para obter essa média pode ser alterado no combo já citado num painel anterior. Já o valor médio pode ser obtido também através das configurações do Grafana, no lado direito, na opção \"Value options --> Calculation --> Mean\"."
   }
  },
  {
   "title": "Dispositivo ID = 10c325",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "from(bucket:\"devices\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._measurement == \"10c325\" and r._field == \"dojot.temperatura\")\n|> map(fn: (r) => ({r with Temperatura: float(v: r._value)}))\n|> keep(columns: [\"Temperatura\", \"_time\"])\n|> limit(n: ${limitVar})"
    }
   ]
  },
  {
   "title": "Painel 4",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": {
    "content": "# Linha com 1 atributo para 1 dispositivo limitando a quantidade de pontos por variável\n\nNesse painel, estamos limitando a quantidade de itens consultados na query através da função \"limit\" e com a variável \"limitVar\" que pode ser carregada através do combo \"Limite\" lá no topo."
   }
  },
  {
   "title": "Dispositivo ${device}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "query": "from(bucket:\"devices\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._measurement == \"${deviceId}\" and r._field == \"dojot.temperatura\")\n|> map(fn: (r) => ({r with Temperatura: float(v: r._value)}))\n|> keep(columns: [\"Temperatura\", \"_time\"])"
    }
   ]
  },
  {
   "title": "Painel 5",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "options": {
    "content": "# Linha com 1 atributo para 1 dispositivo variável\n\nNesse painel, o nome do dispositivo que está no título é obtido através de uma variável que é carregada através da seleção do combo \"Nome do dispositivo\", no topo, no canto esquerdo, pelo usuário. Nesse combo o usuário pode selecionar apenas um dispositivo de cada vez. Já na query que é executada na linguagem Flux, é utilizado o ID do dispositivo (também com uma variável) ao invés do nome, mesmo sem o usuário ter escolhido explicitamente um ID. Isso ocorre pois ao selecionar um nome de dispositivo no combo, uma nova consulta ao banco de dados é feita para obter o ID, atribuindo na variável de forma transparente ao usuário. Isso também só foi possível devido ao nome do dispositivo ser único no banco de dados, não sendo possível existir 2 nomes de dispositivos iguais."
   }
  },
  {
   "title": "Dispositivo ID = 10c325",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "query": "from(bucket:\"devices\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._measurement == \"${deviceId}\" and r._field == \"dojot.${field}\")\n|> map(fn: (r) => ({r with Temperatura: float(v: r._value)}))\n|> keep(columns: [\"Temperatura\", \"_time\"])"
    }
   ]
  },
  {
   "title": "Painel 6",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "options": {
    "content": "# Linha com 1 atributo variável para 1 dispositivo\n\nNesse painel, a query também está usando variável, só que desta vez no atributo. A variável \"field\" é carregada com a seleção do combo \"Atributo\"."
   }
  },
  {
   "title": "Temperatura nos dispositivos: ${devices}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "query": "from(bucket:\"devices\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => contains(value: r[\"_measurement\"], set: ${devicesIds:json}))\n|> filter(fn: (r) => r[\"_field\"] == \"dojot.${field}\")\n|> toFloat()\n|> drop(columns: [\"_field\"])"
    }
   ]
  },
  {
   "title": "Painel 7",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "options": {
    "content": "# Linha com 1 atributo para 2 dispositivos variáveis\n\nNesse painel, a query utiliza uma variável que contém uma lista de IDs que é carregada através da seleção do combo \"Dispositivos\". Nesse combo é possível selecionar mais de um dispositivo de uma vez. Assim como num painel anterior, aqui também usa-se o nome dos dispositivos no combo, porém, usa-se os IDs na query. Nesse painel selecionamos 2 dispositivos na lista, mas é possível inserir mais, sendo recomendado, nesse caso, atualizar a configuração \"override\", já explicada anteriormente, para que os novos dispositivos exibam a unidade de medida correta. Na query utilizamos a função drop() para ocultar o nome do atributo no gráfico, deixando apenas o ID do dispositivo."
   }
  },
  {
   "title": "Device ${device}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket:\"devices\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._measurement == \"${deviceId}\" and r._field == \"dojot.${field}\")\n|> map(fn: (r) => ({r with Temperatura: float(v: r._value)}))\n|> keep(columns: [\"Temperatura\", \"_time\"])"
    }
   ]
  },
  {
   "title": "Painel 8",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "options": {
    "content": "# Linha/área com 1 atributo para 1 dispositivo com uso de limites\n\nPainel parecido com outros anteriores, mas com o uso de cores no gráfico conforme os valores dos atributos. Essa configuração do Grafana é feita no lado direito, na opção \"Add field override\", que é a última opção do lado direito. Após clicar nela, foi selecionada a opção \"Fields with name\" -> \"Add override property\" -> \"Thresholds\"."
   }
  },
  {
   "title": "Device ${device}",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"devices\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._measurement == \"${deviceId}\" and r._field == \"dojot.${field}\")\n|> map(fn: (r) => ({r with Temperatura: float(v: r._value)}))\n|> keep(columns: [\"Temperatura\", \"_time\"])"
    }
   ]
  },
  {
   "title": "Painel 9",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "options": {
    "content": "# \"Label\" com último valor de 1 atributo para 1 dispositivo, contendo os últimos pontos na base do gráfico\n\nNesse painel estamos usando a opção \"Stat\" lá em cima, à direita, nas configurações do Grafana, no tipo de gráfico, e em \"Value options\" -> \"Calculation\" selecionamos \"Last\" para que seja exibido o valor mais atual de temperatura. Embaixo do valor que é exibido no painel, é exibido uma gráfico no estilo time-series com um \"resumo\" das temperaturas obtidas no período escolhido."
   }
  },
  {
   "title": "Device ${device}",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"devices\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._measurement == \"${deviceId}\" and r._field == \"dojot.${field}\")\n|> map(fn: (r) => ({r with Temperatura: float(v: r._value)}))\n|> keep(columns: [\"Temperatura\", \"_time\"])"
    }
   ]
  },
  {
   "title": "Painel 10",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "options": {
    "content": "# \"Gauge\" com último valor de 1 atributo para 1 dispositivo\n\nNesse painel estamos usando a opção \"Gauge\" lá em cima, à direita, nas configurações do Grafana, no tipo de gráfico, e em \"Value options\" -> \"Calculation\" selecionamos \"Last\" para que seja exibido o valor mais atual de temperatura. Esse gauge está utilizando a configuração default nos valores limite, ou seja, os valores mínimo e máximo que serão considerados no gauge são o menor e o maior valor contidos na lista retornada pela consulta."
   }
  },
  {
   "title": "Device ${device}",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"devices\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._measurement == \"${deviceId}\" and r._field == \"dojot.${field}\")\n|> map(fn: (r) => ({r with Temperatura: float(v: r._value)}))\n|> keep(columns: [\"Temperatura\", \"_time\"])"
    }
   ]
  },
  {
   "title": "Painel 11",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "options": {
    "content": "# \"Gauge\" com último valor de 1 atributo para 1 dispositivo com uso de limites\n\nParecido com o painel anterior, porém, ao invés de valores default nos limites, estamos configurando os limites na parte de configurações do Grafana no lado direito, em \"Standard options\", valor mínimo = 0 e valor máximo = 40. Utilizamos também thresholds para exibir os valores por cores."
   }
  },
  {
   "title": "Localização dispositivo ${device}",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "targets": [
    {
     "query": "from(bucket:\"devices\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._measurement == \"${deviceId}\")\n|> filter(fn: (r) => r._field == \"dojot.latitude\" or r._field == \"dojot.longitude\")\n|> toFloat()\n|> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n|> drop(columns: [\"_start\", \"_stop\", \"_time\"])"
    }
   ]
  },
  {
   "title": "Painel 12",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "options": {
    "content": "# Mapa para exibir posição de latitude e longitude\n\nNesse painel estamos exibindo a localização de um dispositivo no mapa, através da latitude e longitude (que devem ser do tipo float). A query precisa usar a função pivot() para que essa exibição no mapa funcione, pois essa função coloca os atributos latitude e longitude numa linha só (já que originalmente esses atributos estão em linhas diferentes no InfluxDB, na coluna \"_field\"), e o Geomap precisa desses atributos \"alinhados\". Já a função drop() está ocultando alguns dados desnecessários e deixando só latitude e longitude para serem exibidos no mapa, ao passar o mouse sobre o ponto da localização. Na parte de configurações, selecionamos os nomes dos atributos de latitude e longitude em \"Data Layer\" -> \"Location\" -> \"Coords\"."
   }
  }
 ]
}