## This role is responsible for deploying Minio for dojot

- name: dojot - Minio Objects
  k8s:
    kubeconfig: "{{ dojot_kubeconfig_file_path | default(omit) }}"
    state: present
    definition: "{{ item }}"
  register: result
  until: result.failed == 0
  retries: 30
  delay: 10
  loop:
  - "{{ lookup('template', 'minio_service.yaml.j2') | from_yaml }}"
  - "{{ lookup('template', 'minio_statefulset.yaml.j2') | from_yaml }}"