## This role is responsible for deploying the Persister Service for dojot

- name: dojot - Persister deployment
  k8s:
    kubeconfig: "{{ dojot_kubeconfig_file_path | default(omit) }}"
    state: present
    definition: "{{ lookup('template', 'persister_deployment.yaml.j2') | from_yaml }}"
  register: result
  until: result.failed == 0
  retries: 30
  delay: 10
