## This role is responsible for deploying the Image Manager Service for dojot

- name: dojot - Image Manager Objects
  k8s:
    kubeconfig: "{{ dojot_kubeconfig_file_path | default(omit) }}"
    state: present
    definition: "{{ item }}"
  register: result
  until: result.failed == 0
  retries: 30
  delay: 10
  loop:
  - "{{ lookup('template', 'image_manager_service.yaml.j2') | from_yaml }}"
  - "{{ lookup('template', 'image_manager_secrets.yaml.j2') | from_yaml }}"
  - "{{ lookup('template', 'image_manager_deployment.yaml.j2') | from_yaml }}"
