
# Create the dojot namespace that will be used for deployment

- name: dojot - Create dojot namespace
  k8s:
    kubeconfig: "{{ dojot_kubeconfig_file_path | default(omit) }}"
    state: present
    definition: "{{ lookup('template', 'namespace.yaml.j2') | from_yaml }}"
  register: result
  until: result.failed == 0
  retries: 30
  delay: 10
