const express = require('express');

const expressWS = require('express-ws');

const addRequestId = require('express-request-id');

const compression = require('compression');

const createError = require('http-errors');

const HttpStatus = require('http-status-codes');

const morgan = require('morgan');

const jwt = require('express-jwt');

/* This library is about what happens when you hit an async error. */
require('express-async-errors');

const { Logger } = require('@dojot/microservice-sdk');

const { app: appCfg, server: servCfg, nodeEnv } = require('./Config');

Logger.setTransport('console', {
  level: appCfg.log.log_console_level,
});
if (appCfg.log.log_file) {
  Logger.setTransport('file', {
    level: appCfg.log.log_file_level,
    filename: appCfg.log.log_file_filename,
  });
}
Logger.setVerbose(appCfg.log.log_verbose);

const app = express();
const getTicketRouter = require('./routes/TicketRouter');
const getTopicsRouter = require('./routes/TopicsRouter');

function configure(server) {
  const logger = new Logger();
  logger.info('Configuring the Express Application...');

  /* Lets it define WebSocket endpoints like any other type of route
   * and applies regular Express middleware. */
  expressWS(app, server);

  /* Generate UUID for request and add it to X-Request-Id header.
   * In case request contains X-Request-Id header, uses its value instead. */
  app.use(addRequestId());

  /* compress all responses */
  app.use(compression());

  /* setup the logger */
  logger.stream = {
    write: (message) => {
      logger.info(message);
    },
  };
  morgan.token('id', (req) => req.id);

  app.use(morgan(appCfg.morganLogFormat, { stream: logger.stream }));

  /* To connect to the server via a websocket, the client application
   * needs a "ticket", this ticket is a simple JWT (token), but in order
   * to avoid confusion with the User Access Token (generated by IAM),
   * we will call this one just "ticket", as it can only be used once
   * and in a very short period of time. */
  app.use(jwt({
    secret: appCfg.ticket.secret,
    credentialsRequired: false,
    requestProperty: 'ticket',
    getToken: (req) => {
      if (req.headers.authorization) {
        const authHeader = req.headers.authorization.split(' ');
        if (authHeader.length === 2 && authHeader[0] === 'Bearer') {
          return authHeader[1];
        }
      } else if (req.query && req.query.ticket) {
        return req.query.ticket;
      }
      if (servCfg.jwt_header_auth) {
        const err = new createError.Unauthorized();
        err.message = 'Missing ticket';
        throw err;
      }
      return null;
    },
  }).unless({ path: [/ticket$/ig] }));

  /* Open API - Routes available through the API Gateway */
  app.use('/api/v1',
    getTicketRouter(),
    getTopicsRouter());

  /* catch 404 and forward to error handler */
  app.use((req, res, next) => {
    next(new createError.NotFound());
  });

  /* default error handler */
  app.use((err, req, res, next) => {
    if (res.headersSent) {
      return next(err);
    }
    const status = err.status || 500;
    if (err.name === 'UnauthorizedError') {
      res.sendStatus(HttpStatus.UNAUTHORIZED);
    } else if (status === 500 && nodeEnv !== 'development') {
      logger.error(err.message);
      res.status(status).json({ message: 'An unexpected error has occurred.' });
    } else if (err.responseBody) {
      res.status(status).json(err.responseBody);
    } else if (err.message) {
      logger.error(err);
      res.status(status).json({ message: err.message });
    } else {
      res.sendStatus(status);
    }
    return null;
  });

  logger.info('Express Application successfully configured!');
}

module.exports = {
  expressApp: app,
  configure,
};
