version: "3.8"
services:
  x509-identity-mgmt:
    build:
      context: ./../../x509-identity-mgmt/
    depends_on:
      - x509-ejbca
      - postgres
      - mongodb
    restart: always
    environment:
      NODE_ENV: production
      X509IDMGMT_MONGO_CONN_URI: "mongodb://mongodb:27017/x509-identity-mgmt"
      X509IDMGMT_MONGO_CONN_OPTIONS_USER: root
      X509IDMGMT_MONGO_CONN_OPTIONS_PASS: pass
      X509IDMGMT_MONGO_CONN_OPTIONS_AUTHSOURCE: admin
      X509IDMGMT_EJBCA_HEALTHCHECK_URL: "http://x509-ejbca:8080/ejbca/publicweb/healthcheck/ejbcahealth"
      X509IDMGMT_EJBCA_WSDL: "https://x509-ejbca:8443/ejbca/ejbcaws/ejbcaws?wsdl"
      # ROARR_LOG: "true" # healthcheck is using 'Roarr' to implement logging.
    ports:
      - "3000:3000"
    volumes:
      - "ejbca-client-tls-volume:/opt/tls"
    networks:
      - x509idmgmt-ejbca-bridge
      - x509idmgmt-mongo-bridge
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:9000/health"]
      interval: 10s
      timeout: 10s
      retries: 6
      start_period: 2m

  x509-ejbca: # this service cannot be called 'ejbca'
    build:
      context: ./../../ejbca/
    depends_on:
      - postgres
    restart: always
    hostname: "x509-ejbca" # The 'hostname' must have the same name as the 'service'
                           # and cannot be called 'ejbca' so as not to conflict with
                           # the ejbca's internal End-Entity (hidden)
    domainname: "" # the 'domainname' must remain empty unless the
                   # service name contains periods (such as an FQDN)
    environment:
      DATABASE_JDBC_URL: jdbc:postgresql://postgres:5432/ejbca?characterEncoding=UTF-8
      DATABASE_USER: ejbca
      DATABASE_PASSWORD: ejbca
      EJBCA_EXTERNAL_ACCESS: "true"
      EJBCA_ADMIN_USER: "true"
      # EJBCA_SERVER_CERT_REGEN: "true" # Used to force the generation of a new certificate for the server
      # EJBCA_LOCK_FILE_TIMEOUT: "0" # Used to break the '.lock' file
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - "ejbca-volume:/mnt/persistent"
      - "ejbca-client-tls-volume:/opt/tls"
    networks:
      - x509idmgmt-ejbca-bridge
      - ejbca-postgres-bridge
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8080/ejbca/publicweb/healthcheck/ejbcahealth"]
      interval: 30s
      timeout: 10s
      retries: 2
      start_period: 2m

  postgres:
    image: "postgres:9.4.24-alpine"
    restart: always
    environment:
      POSTGRES_DB: ejbca
      POSTGRES_USER: ejbca
      POSTGRES_PASSWORD: ejbca
    ports:
      - "5432:5432"
    volumes:
      - "postgres-volume:/var/lib/postgresql/data"
    networks:
      - ejbca-postgres-bridge
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "ejbca"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres
    restart: always
    ports:
      - 5050:80
    volumes:
      - pgadmin-volume:/var/lib/pgadmin
    networks:
      - ejbca-postgres-bridge

  mongodb:
    image: "mongo"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - "27017:27017"
    volumes:
      - "mongodb-volume:/data/db"
      - "mongodb-cfg-volume:/data/configdb"
    networks:
      - x509idmgmt-mongo-bridge

  mongo-webadmin:
    image: "mongo-express"
    restart: always
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: ambiance
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
    ports:
      - "6060:8081"
    networks:
      - x509idmgmt-mongo-bridge

volumes:
  ejbca-client-tls-volume:
  ejbca-volume:
  postgres-volume:
  mongodb-volume:
  mongodb-cfg-volume:
  pgadmin-volume:

networks:
  x509idmgmt-ejbca-bridge:
    driver: bridge
  x509idmgmt-mongo-bridge:
    driver: bridge
  ejbca-postgres-bridge:
    driver: bridge
