version: '3'
services:

  redis:
    image: dojot/redis:6.0.4-alpine3.11
    restart: always
    ports:
      - 6379:6379 #For tests running externally
    # TODO: add tls example
    # volumes:
    #   - ./redis.conf:/usr/local/etc/redis/redis.conf
    logging:
      driver: json-file
      options:
        max-size: 100m

  zookeeper:
    image: dojot/zookeeper:3.4
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 100m

  kafka:
    image: dojot/wurstmeister-kafka:2.12-2.1.1
    depends_on:
      - zookeeper
    restart: always
    ports:
      - 9092:9092 #For tests running externally
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_TOPICS: 'tenant1.ws.example.test,tenant2.ws.example.test'
    logging:
      driver: json-file
      options:
        max-size: 100m

  kafkacat-producer:
    image: dojot/confluentinc-cp-kafkacat:5.0.4-1
    depends_on:
      - kafka
    restart: always
    command: /bin/bash -c "/kafkacat-producer.sh"
    volumes:
      - ./kafkacat-producer.sh:/kafkacat-producer.sh:Z
    logging:
      driver: json-file
      options:
        max-size: 100m

  kafka-ws-example:
    build:
      context: ./../../
      dockerfile: ./Dockerfile
    depends_on:
      - kafka
      - redis
    environment:
      NODE_ENV: development # To detail error messages
      KAFKA_WS_CONSUMER_METADATA_BROKER_LIST: kafka:9092
      KAFKA_WS_CONSUMER_GROUP_ID: kafka-ws-example
      KAFKA_WS_LOGGER_TRANSPORTS_CONSOLE_LEVEL: debug
      KAFKA_WS_LOGGER_VERBOSE: "true"
      KAFKA_WS_LOGGER_TRANSPORTS_FILE_ENABLE: "true"
      KAFKA_WS_LOGGER_TRANSPORTS_FILE_LEVEL: debug
      KAFKA_WS_SERVER_PORT: 5000
      KAFKA_WS_SERVER_HOST: 0.0.0.0
      KAFKA_WS_SERVER_JWT_EXP_TIME: "true"
      KAFKA_WS_SERVER_MAX_LIFE_TIME: 120
      # tls example
      # KAFKA_WS_SERVER_TLS: "true"
      # KAFKA_WS_SERVER_TLS_CA_FILE: /certs/ca-cert.pem
      # KAFKA_WS_SERVER_TLS_KEY_FILE: /certs/server-key.pem
      # KAFKA_WS_SERVER_TLS_CERT_FILE: /certs/server-cert.pem
    restart: always
    ports:
      - 5000:5000 #For tests running externally
    logging:
      driver: json-file
      options:
        max-size: 100m
    # tls example
    # volumes:
    #  - ./certs/server/:/certs/:Z
    # to dev
    # volumes:
    #  - ../app/:/opt/kafka-ws/app/:Z # need to run before 'npm run parser:compile'
    # command: ["npm", "run", "dev"]

  ws-client-sample-0:
    build:
      context: ./WSClient/
      dockerfile: ./Dockerfile
    environment:
      WS_HOST: "kafka-ws-example"
      WS_PORT: 5000
      # tls example
      # WS_TLS: "true"
      # WS_TLS_CA_FILE: /certs/ca-cert.pem
      # WS_TLS_KEY_FILE: /certs/client-key.pem
      # WS_TLS_CERT_FILE: /certs/client-cert.pem
    depends_on:
      - kafka-ws-example
    restart: always
    command: ["node", "Client.js","0"]
    logging:
      driver: json-file
      options:
        max-size: 100m
    # tls example
    # volumes:
    #   - ./certs/client/:/certs/:Z

  ws-client-sample-1:
    build:
      context: ./WSClient/
      dockerfile: ./Dockerfile
    environment:
      WS_HOST: "kafka-ws-example"
      WS_PORT: 5000
      # tls example
      # WS_TLS: "true"
      # WS_TLS_CA_FILE: /certs/ca-cert.pem
      # WS_TLS_KEY_FILE: /certs/client-key.pem
      # WS_TLS_CERT_FILE: /certs/client-cert.pem
    depends_on:
      - kafka-ws-example
    restart: always
    command: ["node", "Client.js","1"]
    logging:
      driver: json-file
      options:
        max-size: 100m
    # tls example
    # volumes:
    #   - ./certs/client/:/certs/:Z