# TODO: improve this example to use the best practices
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  labels:
    name: client
    app: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example
      name: client
  template:
    metadata:
      labels:
        name: client
        app: example
    spec:
      restartPolicy: Always
      containers:
      - name: app-container
        image: mprevide/sidecar-client
        livenessProbe:
          httpGet:
            path: /live # from sidecar-container
            port: 9000
          failureThreshold: 3 #times before giving up and restarting the container
          initialDelaySeconds: 10
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        startupProbe:
          httpGet:
            path: /live
            port: 9000
          failureThreshold: 30
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        volumeMounts:
        - mountPath: /certs
          name: shared-certs
      - name: sidecar-container
        image: mprevide/cert-sidecar
        env:
          - name: CERT_SC_APP_SIDECAR_TO
            value: 'client'
          - name: CERT_SC_USER_CONFIG_FILE
            value: 'simple.conf'
          - name: CERT_SC_LOG_CONSOLE_LEVEL
            value: 'debug'
          # - name: CERT_SC_CRON_CRL
          #   value: 'true'
          # - name: CERT_SC_CRON_CRL_TIME
          #   value: '* * * * *'
          # - name: CERT_SC_CERTS_CRL
          #   value: 'true'
        readinessProbe:
          httpGet:
            path: /ready
            port: 9000
          failureThreshold: 1 #times before giving up will be marked Unready
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /live
            port: 9000
          failureThreshold: 3 #times before giving up will restarting the container
          initialDelaySeconds: 10
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        startupProbe:
          httpGet:
            path: /live
            port: 9000
          failureThreshold: 30
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        volumeMounts:
        - mountPath: /certs
          name: shared-certs
      volumes:
        - name: shared-certs
          emptyDir: {}