apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    name: postgres
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    name: postgres
    app: example
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    name: postgres
    app: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example
      name: postgres
  template:
    metadata:
      labels:
        name: postgres
        app: example
    spec:
      restartPolicy: Always
      containers:
        - image: dojot/postgres:9.5.21-alpine
          name: postgres
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: postgres