# TODO: improve this example to use the best practices
apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    name: server
spec:
  type: ClusterIP
  ports:
  - port: 8888
    targetPort: 8888
  selector:
    name: server
    app: example
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    name: server
    app: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example
      name: server
  template:
    metadata:
      labels:
        name: server
        app: example
    spec:
      restartPolicy: Always
      containers:
      - name: app-container
        image: mprevide/sidecar-server
        livenessProbe:
          httpGet:
            path: /live # from sidecar-container
            port: 8889
          failureThreshold: 3  #times before giving up and restarting the container
          initialDelaySeconds: 10
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        volumeMounts:
        - mountPath: /certs
          name: shared-certs
      - name: sidecar-container
        image: mprevide/cert-sidecar
        readinessProbe:
          httpGet:
            path: /ready
            port: 8889
          failureThreshold: 1 #times before giving up will be marked Unready
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /live
            port: 8889
          failureThreshold: 3 #times before giving up will restarting the container
          initialDelaySeconds: 10
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        startupProbe:
          httpGet:
            path: /live
            port: 8889
          failureThreshold: 30
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        env:
          - name: CERT_SC_APP_SIDECAR_TO
            value: 'server'
          - name: CERT_SC_USER_CONFIG_FILE
            value: 'simple.conf'
          - name: CERT_SC_CERTS_HOSTNAMES
            value: '["server"]'
          - name: CERT_SC_LOG_CONSOLE_LEVEL
            value: 'debug'
          # - name: CERT_SC_CRON_CRL
          #   value: 'true'
          # - name: CERT_SC_CRON_CRL_TIME
          #   value: '* * * * *'
          # - name: CERT_SC_CERTS_CRL
          #   value: 'true'
        volumeMounts:
        - mountPath: /certs
          name: shared-certs
      volumes:
        - name: shared-certs
          emptyDir: {}