FROM node:16.17.1-alpine AS base

WORKDIR /opt/report-manager

RUN apk --no-cache add \
  bash \
  g++ \
  ca-certificates \
  lz4-dev \
  musl-dev \
  cyrus-sasl-dev \
  openssl-dev \
  make \
  python3 \
  && \
  apk add --no-cache --virtual \
  .build-deps \
  gcc \
  zlib-dev \
  libc-dev \
  bsd-compat-headers \
  py-setuptools \
  bash

COPY package.json ./package.json
COPY yarn.lock ./yarn.lock
COPY .swcrc ./.swcrc
COPY tsconfig.json ./tsconfig.json
COPY prisma ./prisma/

RUN yarn install

COPY src ./src

RUN yarn build

FROM node:16.17.1-alpine

WORKDIR /opt/report-manager

RUN apk --no-cache add \
  libsasl \
  lz4-libs \
  openssl \
  tini \
  curl

COPY --from=base /opt/report-manager /opt/report-manager

ENTRYPOINT ["/sbin/tini", "--"]

CMD ["yarn", "start"]

HEALTHCHECK --start-period=2m --interval=30s --timeout=10s --retries=3 \
  CMD curl -f http://localhost:9000/health || exit 1
