## This role is responsible for deploying the IoT Agent Lwm2m Service for dojot

- name: dojot - IoT Agent Lwm2m Objects
  k8s:
    kubeconfig: "{{ dojot_kubeconfig_file_path | default(omit) }}"
    state: present
    definition: "{{ item }}"
  register: result
  until: result.failed == 0
  retries: 30
  delay: 10
  loop:
  - "{{ lookup('template', 'iotagent_lwm2m_service.yaml.j2') | from_yaml }}"
  - "{{ lookup('template', 'iotagent_lwm2m_deployment.yaml.j2') | from_yaml }}"