FROM golang:1.18.7-alpine3.16 AS base

WORKDIR /opt/

RUN apk --no-cache add git

RUN git clone https://github.com/influxdata/telegraf
WORKDIR /opt/telegraf

RUN git checkout release-1.24
COPY plugins/inputs/kafka_consumer_vdojot/ ./plugins/inputs/kafka_consumer_vdojot/
COPY plugins/inputs/all/kafka_consumer_vdojot.go ./plugins/inputs/all/kafka_consumer_vdojot.go

COPY plugins/outputs/dojot_organization_creator/ ./plugins/outputs/dojot_organization_creator/
COPY plugins/outputs/all/dojot_organization_creator.go ./plugins/outputs/all/dojot_organization_creator.go

COPY plugins/outputs/influxdb_vdojot ./plugins/outputs/influxdb_vdojot/
COPY plugins/outputs/all/influxdb_vdojot.go ./plugins/outputs/all/influxdb_vdojot.go
COPY dojot-telegraf.sh ./dojot-telegraf.sh

CMD ["tail", "-f", "/dev/null"]