## This role is responsible for deploying postgreSQL for dojot

- name: dojot - EJBCA-PostgreSQL Persistent Volume Claim
  when: dojot_ejbca_psql_persistent_volumes
  k8s:
    kubeconfig: "{{ dojot_kubeconfig_file_path | default(omit) }}"
    state: present
    definition: "{{ lookup('template', 'postgres_storage.yaml.j2') | from_yaml }}"
  register: result
  until: result.failed == 0
  retries: 30
  delay: 10

- name: dojot - EJBCA-PostgreSQL Objects
  k8s:
    kubeconfig: "{{ dojot_kubeconfig_file_path | default(omit) }}"
    state: present
    definition: "{{ item }}"
  register: result
  until: result.failed == 0
  retries: 30
  delay: 10
  loop:
  - "{{ lookup('template', 'postgres_service.yaml.j2') | from_yaml }}"
  - "{{ lookup('template', 'z_postgres_cluster.yaml.j2') | from_yaml }}"
