name: Device Manager Batch (device/device-manager-batch)

# Triggered after a branch is created, a tag or a branch is pushed or a PR with changes in
# 'device/device-manager-batch/**' is submitted
on:
  create:
  push:
  pull_request:
    paths:
      - 'device/device-manager-batch/**'

jobs:
  unit-tests:
    # Path to help identify each job in the status checks
    name: (device/device-manager-batch) Unit Tests
    # If the commit message contains 'ci skip', it is not necessary to run this job
    if: contains(github.event.head_commit.message, 'ci skip') == false
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [16.x]
    steps:

    - name: checkout
      uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm ci, unit-test, build, eslint:lint, check-licenses
      run: |
        cd device/device-manager-batch
        npm ci
        npm run unit-test
        npm run build --if-present
        npm run eslint:lint
        npm run check-licenses

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        # Created when 'npm test' was executed
        directory: device/device-manager-batch/coverage
        # Flags allow you to isolate coverage reports for different tests
        flags: device-manager-batch
        # Custom name for the upload
        name: device-manager-batch

  docker-hub:
    needs: unit-tests
    # Path to help identify each job in the status checks
    name: (device/device-manager-batch) Build and Publish image to DockerHUb
    runs-on: ubuntu-latest
    # If this is a PR, it won't run
    if: contains(github.ref, 'refs/pull/') == false
    steps:

    - name: Owner Repository
      id: get_owner
      run: |
        export OWNER=$(echo ${{ github.repository }} | cut -f1 -d"/")
        echo Current Owner is $OWNER
        echo ::set-output name=owner::$OWNER
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build and Push
      uses: elgohr/Publish-Docker-Github-Action@2.16
      with:
        name: ${{ steps.get_owner.outputs.owner }}/device-manager-batch
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: device/device-manager-batch
        # Label with the built image's commit
        buildoptions: " --label 'commit_sha'='${{ github.sha }}' "
        # Whether tag will be based in the branch name or in the tag name
        tag_names: true