apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: node-exporter
  name: node-exporter
  namespace: monitoring
spec:
  clusterIP: None
  ports:
  - name: https
    port: 9100
    targetPort: https
  selector:
    app: node-exporter

  # The perf collector may not work by default on all Linux systems due to kernel configuration and security settings. To allow access, set the following sysctl parameter:

  #   sysctl -w kernel.perf_event_paranoid=X
  #   2 allow only user-space measurements (default since Linux 4.6).
  #   1 allow both kernel and user measurements (default before Linux 4.6).
  #   0 allow access to CPU-specific data but not raw tracepoint samples.
  #   -1 no restrictions.
